name: nvfetcher
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  repository_dispatch:
jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: 'nvfetcher generate'
        run: nix-shell -p nvfetcher --command "nvfetcher -v"
      - name: 'Check update'
        run: 'git diff --quiet --exit-code _sources/generated.nix'
      - name: Commit files
        if: '${{ failure() }}'
        run: |
          git config --local user.email "action@miao.dev"
          git config --local user.name "nvfetcher action"
          git commit -a -m "Update nvfetcher"
      - name: Push back changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
