name: nvfetcher
on:
  schedule:
    - cron: '10 5 * * *'
  workflow_dispatch:
  repository_dispatch:
jobs:
  nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: 'nvfetcher generate'
        run: nix-shell -p nvfetcher --command "nvfetcher -v --keep-going"
      - name: Commit files
        id: commit-files
        run: |
          nix-shell -p git-crypt
          set +e
          git diff --quiet --exit-code _sources/generated.nix
          changed=$?
          echo "changed=$changed" >> $GITHUB_OUTPUT
          [ $changed = 0 ] && echo "Nothing changed, early exiting" && exit
          echo "Changed, commit & push"
          git config --local user.email "action@miao.dev"
          git config --local user.name "nvfetcher action"
          git commit _sources -m "Update generated dependencies"
      - name: Push changes
        if: '${{ steps.commit-files.outputs.changed == 1 }}'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
